### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by mleclair73** [alexcrist/climbing-tick-list#1]
Fun House is two words. This is a v important & blocking issue pls fix asap
NO: https://www.mountainproject.com/search?q=Funhouse%20Cathedral
YES: https://www.mountainproject.com/search?q=Fun%20house%20Cathedral

**Comment by alexcrist** [comment]
omg i'll get on this FOOKING immediately

**Comment by alexcrist** [comment]
cb636e3e43932f3d0b945bdfaf0148e72afbf53a
